{
 "title": "substrate",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "swap_ram",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "resource_swap_use{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "resource_swap_use{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "ram",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "resource_ram_use{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "resource_ram_use{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "resource_disk_use{instance=\"10.10.10.41:33332\",mount_point=\"/\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "resource_disk_use{instance=\"15.164.134.70:33333\",mount_point=\"/\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "CPU USED",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "resource_cpu_use{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "resource_cpu_use{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "network-receive",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "resource_receive_bytes_per_sec{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "resource_receive_bytes_per_sec{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "network-send",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "resource_send_bytes_per_sec{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "resource_send_bytes_per_sec{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  { "title": "Kusama", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "block precommit sign",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "consensus_validator_block_sign_precommit{validator_address=\"5CKmh25ZCXsof1iHLjVTAZWq8oo2qwit4gqG6zgGv6phfyVw\",instance=\"10.10.10.41:33332\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "kusama_best_block",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "consensus_best_block_height_number{instance=\"10.10.10.41:33332\"}"
    }
   ]
  },
  {
   "title": "CPU load %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "consensus_node_cpu{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "consensus_node_cpu{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "peers_num",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p2p_peers_number{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "p2p_peers_number{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "tx num",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consensus_num_txs{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "consensus_num_txs{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "block prevote sign",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "consensus_validator_block_sign_prevote{validator_address=\"5CKmh25ZCXsof1iHLjVTAZWq8oo2qwit4gqG6zgGv6phfyVw\",instance=\"10.10.10.41:33332\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "kusama_finality_block",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "consensus_finality_block_height_number{instance=\"10.10.10.41:33332\"}"
    }
   ]
  },
  {
   "title": "mempool_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consensus_node_memory{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "consensus_node_memory{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "send_byte_per_sec",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "p2p_peers_send_byte_per_sec{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "p2p_peers_send_byte_per_sec{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "receive_byte_per_sec",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "p2p_peers_receive_byte_per_sec{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "p2p_peers_receive_byte_per_sec{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "consensus_node_memory{instance=\"10.10.10.41:33332\"}",
     "legendFormat": "kusama-sentry"
    },
    {
     "expr": "consensus_node_memory{instance=\"15.164.134.70:33333\"}",
     "legendFormat": "kusama-validator"
    }
   ]
  }
 ]
}